// LOGIN
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// LOGOUT
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// USER LOADING
export const USER_LOADING_REQUEST = "USER_LOADING_REQUEST";
export const USER_LOADING_SUCCESS = "USER_LOADING_SUCCESS";
export const USER_LOADING_FAILURE = "USER_LOADING_FAILURE";

// CLEAR ERROR
export const CLEAR_ERROR_REQUEST = "CLEAR_ERROR_REQUEST";
export const CLEAR_ERROR_SUCCESS = "CLEAR_ERROR_SUCCESS";
export const CLEAR_ERROR_FAILURE = "CLEAR_ERROR_FAILURE";

// MEMBER UPLOADING
export const MEMBER_UPLOADING_REQUEST = "MEMBER_UPLOADING_REQUEST";
export const MEMBER_UPLOADING_SUCCESS = "MEMBER_UPLOADING_SUCCESS";
export const MEMBER_UPLOADING_FAILURE = "MEMBER_UPLOADING_FAILURE";

// MEMBER LIST
export const MEMBER_LIST_REQUEST = "MEMBER_LIST_REQUEST";
export const MEMBER_LIST_SUCCESS = "MEMBER_LIST_SUCCESS";
export const MEMBER_LIST_FAILURE = "MEMBER_LIST_FAILURE";

// MEMBER DELETE
export const MEMBER_DELETE_REQUEST = "MEMBER_DELETE_REQUEST";
export const MEMBER_DELETE_SUCCESS = "MEMBER_DELETE_SUCCESS";
export const MEMBER_DELETE_FAILURE = "MEMBER_DELETE_FAILURE";


// REGISTER
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

// Password Edit
export const PASSWORD_EDIT_UPLOADING_REQUEST =
  "PASSWORD_EDIT_UPLOADING_REQUEST";
export const PASSWORD_EDIT_UPLOADING_FAILURE =
  "PASSWORD_EDIT_UPLOADING_FAILURE";
export const PASSWORD_EDIT_UPLOADING_SUCCESS =
  "PASSWORD_EDIT_UPLOADING_SUCCESS";